package dataManipulation;

public enum PossibleIntents {
    SEE_DATES,
    GENERATE_TODO_LIST,
    GENERATE_LIST,
    MISC_PARAGRAPH,
    GENERATE_TEST_SCHEDULE,
    RECOMMEND_TEXTBOOK,
    GET_PROFESSOR_INFO,
    GET_LOCATION,
    GET_GRADING_POLICY,
    SYLLABUS_OVERVIEW,
    OFFICE_HOUR_TIMES,
    COURSE_DESCRIPTION,
    UNKNOWN
}
